lavalink:
  server:
    password: "changeme"
    sources:
      spotify: true
      youtube: true
    plugins:
      lavasrc:
        providers:
          - "spotify"
          - "ytsearch"
        spotify:
          clientId: "${SPOTIFY_CLIENT_ID}"
          clientSecret: "${SPOTIFY_CLIENT_SECRET}"
          countryCode: "TW"
          playlistLoadLimit: 10
          albumLoadLimit: 10
          authorization:
            email: "${SPOTIFY_EMAIL}"
            password: "${SPOTIFY_PASSWORD}"
